### ISSUE TITLE
i cant upload files

### ISSUE THREAD

**Issue by adamgodel** [LME2/lme2.github.io#1]
image and font ref files here:
[images-fonts.zip](https://github.com/LME2/lme2.github.io/files/3884206/images-fonts.zip)

**Comment by J-Rohault-dF** [comment]
Do you really want me to use the Gotham font?

**Comment by adamgodel** [comment]
yes

**Comment by J-Rohault-dF** [comment]
It doesn't work really, so right now the font used is times new roman

**Comment by J-Rohault-dF** [comment]
Ok it works now
